# fly.toml app configuration file generated for fcperpetual on 2024-02-25T16:48:55+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'fcperpetual'
primary_region = 'lax'

[build]

[[mounts]]
  source = 'data'
  destination = '/data'

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  max_machines_running = 1
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
